## Uncomment the next line to define a global platform for your project
## platform :ios, '9.0'
#
#target 'CocoaPods-Test' do
#  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#  use_frameworks!
#
#  # Pods for CocoaPods-Test
#
#end

use_frameworks!

target 'CocoaPods-Test' do
  pod 'ScrollableGraphView'
end
